title: Quick Links
description: Button-based navigation page
baseurl: "/Site" # If deploying to GitHub Pages with user/organization site, leave this empty.
url: "https://rajeshphy.github.io" # Change this to your actual GitHub Pages URL

theme: minima
plugins: []
